name: Bump version
on:
  push:
    branches:
      - master

jobs:
  product-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: "$(date +'%y%m%d')"
